/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/presigned-urls": {
    /** Get a presigned URL for file upload */
    post: operations["getPresignedUrl"];
  };
  "/v1/unlock": {
    /** Start the Excel unlock process */
    post: operations["unlockFile"];
  };
  "/v1/status/{job_id}": {
    /** Get the status of an unlock job */
    get: operations["getUnlockStatus"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BaseResponse: {
      /** @description Indicates if the request was successful. */
      ok: boolean;
      /** @description The response data if the request was successful. */
      data: Record<string, unknown> | null;
      error: {
        /** @description An error code. */
        code?: string;
        /** @description A human-readable error message. */
        message?: string;
        /** @description Indicates if the operation can be retried. */
        retryable?: boolean;
      } | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get a presigned URL for file upload */
  getPresignedUrl: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description The name of the file to be uploaded.
           * @example confidential.xlsx
           */
          filename: string;
        };
      };
    };
    responses: {
      /** @description Successfully generated presigned URL. */
      200: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
    };
  };
  /** Start the Excel unlock process */
  unlockFile: {
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description The S3 key of the uploaded file.
           * @example uploads/1234-5678/confidential.xlsx
           */
          s3_key: string;
          /**
           * @description A list of passwords to try.
           * @example [
           *   "pass1",
           *   "pass2"
           * ]
           */
          passwords: string[];
        };
      };
    };
    responses: {
      /** @description Unlock process accepted. */
      202: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
      /** @description Bad request */
      400: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
    };
  };
  /** Get the status of an unlock job */
  getUnlockStatus: {
    parameters: {
      path: {
        /**
         * @description The ID of the job to check.
         * @example job-9876-5432
         */
        job_id: string;
      };
    };
    responses: {
      /** @description Job status retrieved. */
      200: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
      /** @description Job not found. */
      404: {
        content: {
          "application/json": components["schemas"]["BaseResponse"];
        };
      };
    };
  };
}
